server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/accounting
    username: postgres
    password: ${DB_PASSWORD:admin}


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true