server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/accounting
    username: postgres
    password: ${DB_PASSWORD:asiye}

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

# for show the colorful console
  output:
    ansi:
      enabled: ALWAYS
